"""ScummVM game profile auto-detection.

Detects known DOS games that are compatible with ScummVM and provides
profile data (game ID, compatibility level, required files) for the
conversion flow.

The profile database lives in ``data/scummvm-profiles.json`` (bundled)
and can be updated from GitHub at runtime.
"""

from __future__ import annotations

import json
import logging
import os
from pathlib import Path

from cellar.backend._profile_matching import (
    content_root,
    match_files,
    match_gog_ids,
)

log = logging.getLogger(__name__)

_CACHE_DIR = (
    Path(os.environ.get("XDG_CACHE_HOME") or Path.home() / ".cache") / "cellar"
)
_PROFILES_CACHE = _CACHE_DIR / "scummvm-profiles.json"

_PROFILES_URL = (
    "https://raw.githubusercontent.com/macaon/cellar"
    "/main/data/scummvm-profiles.json"
)

_warned_missing = False


# ---------------------------------------------------------------------------
# Loading
# ---------------------------------------------------------------------------

def _bundled_profiles_path() -> Path | None:
    """Return the path to the bundled ScummVM profiles JSON, or ``None``."""
    from cellar.utils.paths import _SRC_DATA, _PKG_DATA, _installed_data_dirs

    candidates = (
        [_SRC_DATA / "scummvm-profiles.json", _PKG_DATA / "scummvm-profiles.json"]
        + [d / "scummvm-profiles.json" for d in _installed_data_dirs()]
    )
    for c in candidates:
        if c.is_file():
            return c
    return None


def load_profiles() -> dict:
    """Load the ScummVM profiles database.

    Resolution order: cached (from GitHub fetch) -> bundled (source/Flatpak).
    Returns the full JSON dict, or an empty ``{"profiles": {}}`` fallback.
    """
    global _warned_missing  # noqa: PLW0603

    for path in (_PROFILES_CACHE, _bundled_profiles_path()):
        if path is not None and path.is_file():
            try:
                data = json.loads(path.read_text(encoding="utf-8"))
                if "profiles" in data:
                    return data
            except (json.JSONDecodeError, OSError) as exc:
                log.warning("Failed to load ScummVM profiles from %s: %s",
                            path, exc)

    if not _warned_missing:
        log.info("No ScummVM profiles database found; ScummVM detection disabled")
        _warned_missing = True
    return {"profiles": {}}


def get_profile(slug: str) -> dict | None:
    """Return the full profile dict for *slug*, or ``None``."""
    db = load_profiles()
    return db.get("profiles", {}).get(slug)


# ---------------------------------------------------------------------------
# Detection
# ---------------------------------------------------------------------------

def _load_cdtree(game_dir: Path) -> set[str]:
    """Load filenames from ``hdd/cdtree.txt`` (generated by disc installer).

    Returns a set of lowercase bare filenames found on the CD.
    """
    cdtree = content_root(game_dir) / "cdtree.txt"
    if not cdtree.is_file():
        return set()
    names: set[str] = set()
    try:
        for line in cdtree.read_text(encoding="utf-8", errors="replace").splitlines():
            # DOSBox DIR /S output lines look like: " SKY     DNR    123,456"
            # or "SKY.DNR" depending on format.  Extract anything that looks
            # like a filename with an extension.
            stripped = line.strip()
            if not stripped or stripped.startswith("Directory") or stripped.startswith("Volume"):
                continue
            # Try to extract 8.3 filename from DIR output columns
            parts = stripped.split()
            if len(parts) >= 1:
                # Could be "FILENAME EXT  SIZE" or "FILENAME.EXT  SIZE"
                first = parts[0]
                if "." in first and not first.startswith("."):
                    names.add(first.lower())
                elif len(parts) >= 2 and parts[1].isalpha() and len(parts[1]) <= 3:
                    names.add(f"{first}.{parts[1]}".lower())
    except OSError:
        pass
    return names


def detect_scummvm_profile(game_dir: Path) -> str | None:
    """Detect whether the DOS game in *game_dir* is ScummVM-compatible.

    Searches the HDD content root for matching files, and also checks
    ``cdtree.txt`` (a CD directory listing generated during disc install)
    for games whose data files live on the CD.

    Returns the profile slug or ``None``.
    """
    db = load_profiles()
    profiles = db.get("profiles", {})
    if not profiles:
        return None

    root = content_root(game_dir)
    cd_filenames = _load_cdtree(game_dir)

    # Pass 1: GOG ID match (highest priority)
    for slug, profile in profiles.items():
        match = profile.get("match", {})
        if match_gog_ids(root, match.get("gog_ids", [])):
            log.info("Detected ScummVM profile %r via GOG ID", slug)
            return slug

    # Pass 2: file fingerprint match (hdd + cdtree.txt)
    for slug, profile in profiles.items():
        match = profile.get("match", {})
        files = match.get("files", [])
        if len(files) < 2:
            continue
        all_found = True
        for f in files:
            bare = f.rsplit("/", 1)[-1].lower()
            # Check hdd first
            if "/" in f:
                from cellar.backend._profile_matching import find_file_casefold
                if find_file_casefold(root, f) is not None:
                    continue
            else:
                from cellar.backend._profile_matching import find_file_recursive
                if find_file_recursive(root, f) is not None:
                    continue
            # Fall back to cdtree.txt
            if bare in cd_filenames:
                continue
            all_found = False
            break
        if all_found:
            log.info("Detected ScummVM profile %r via file fingerprint", slug)
            return slug

    return None


# ---------------------------------------------------------------------------
# Remote fetch
# ---------------------------------------------------------------------------

def fetch_profiles_update(on_complete: callable | None = None) -> None:
    """Download the latest ScummVM profiles database from GitHub.

    Writes to ``~/.cache/cellar/scummvm-profiles.json``.  Intended to be
    called on a background thread.
    """
    try:
        from cellar.utils.http import make_session

        session = make_session()
        resp = session.get(_PROFILES_URL, timeout=15)
        resp.raise_for_status()

        data = resp.json()
        if "profiles" not in data:
            log.warning("Fetched ScummVM profiles JSON missing 'profiles' key")
            if on_complete:
                on_complete(False)
            return

        _CACHE_DIR.mkdir(parents=True, exist_ok=True)
        _PROFILES_CACHE.write_text(
            json.dumps(data, indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8",
        )
        log.info("Updated ScummVM profiles cache (%d profiles)",
                 len(data["profiles"]))
        if on_complete:
            on_complete(True)

    except Exception as exc:
        log.debug("Failed to fetch ScummVM profiles update: %s", exc)
        if on_complete:
            on_complete(False)
